doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        server_version: '16'
        types:
            customer_id:    Crm\Contacts\Infrastructure\Doctrine\Type\CustomerIdType
            customer_email: Crm\Contacts\Infrastructure\Doctrine\Type\CustomerEmailType

    orm:
        auto_generate_proxy_classes: true
        enable_native_lazy_objects: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        mappings:
            CrmContacts:
                type: xml
                dir: '%kernel.project_dir%/packages/crm/src/Contacts/Infrastructure/Doctrine'
                prefix: 'Crm\Contacts\Domain'
                is_bundle: false
