security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        identity:
            id: Identity\Auth\Infrastructure\Security\IdentityUserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern: ^/api/identity/commands/login$
            security: false
        refresh:
            pattern: ^/api/identity/commands/refresh-token$
            security: false
        api:
            pattern: ^/api
            stateless: true
            custom_authenticators:
                - Identity\Auth\Infrastructure\Security\JwtAuthenticator

    access_control:
        - { path: ^/api/identity/commands/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/identity/commands/refresh-token, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
